apiVersion: v2
name: answers-storage
description: Answers-storage service Helm chart
type: application
version: 1.0.1
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
