apiVersion: v2
name: adaptive-training
description: Adaptive-training service Helm chart
type: application
version: 1.0.5
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
