{{- with .Values.guacamole }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}-hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  containers:
    - name: {{ .name }}-pre-install-job
      image: "{{ .image.url }}:{{ .image.tag }}"
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/bash"
        - "-c"
        - | {{- range $k, $v := $.Values.postgresServices }}
          PGPASSWORD={{ $.Values.global.postgres.password }} psql -h {{ $.Values.global.postgres.host }} -p {{ $.Values.global.postgres.port }} -U {{ $.Values.global.postgres.user }} -c 'CREATE USER "{{ $v.dbUser }}";' 2> /dev/null
          PGPASSWORD={{ $.Values.global.postgres.password }} psql -h {{ $.Values.global.postgres.host }} -p {{ $.Values.global.postgres.port }} -U {{ $.Values.global.postgres.user }} -c "ALTER USER \"{{ $v.dbUser }}\" PASSWORD '{{ $v.dbPassword }}';" 2> /dev/null
          PGPASSWORD={{ $.Values.global.postgres.password }} psql -h {{ $.Values.global.postgres.host }} -p {{ $.Values.global.postgres.port }} -U {{ $.Values.global.postgres.user }} -c 'CREATE DATABASE "{{ $v.dbName }}" OWNER "{{ $v.dbUser }}";' 2> /dev/null
          {{- end }}
          cat /srv/initdb.sql | PGPASSWORD={{ $.Values.postgresServices.guacamole.dbPassword }} psql -h {{ $.Values.global.postgres.host }} -p {{ $.Values.global.postgres.port }} -U {{ $.Values.postgresServices.guacamole.dbUser }} -d {{ $.Values.postgresServices.guacamole.dbName }} -f -
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}
