apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: kypo-ingress-microservices
  labels: {{- include "common.labels" (dict "name" .Chart.Name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "HEAD"
      - "PUT"
      - "DELETE"
      - "MKCOL"
      - "COPY"
      - "MOVE"
      - "OPTIONS"
      - "PROPFIND"
      - "PROPPATCH"
      - "LOCK"
      - "UNLOCK"
      - "PATCH"
    accessControlMaxAge: 100
