{{- include "common.deployment.header" (dict "name" .Values.global.kypoSyslogServiceName "replicasCount" .Values.replicasCount "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.kypoSyslogServiceName "ports" .Values.externalPorts "Values" .Values) }}
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
