postgres:
  name: postgres
  image:
    url: postgres
    tag: 13-alpine
  ports:
    - port: 5432
      protocol: TCP
      probe: true
  password: password
  pvc:
    size: 500Mi
    storageClassName: longhorn
