apiVersion: v2
name: kypo-crp-head
description: A Helm umbrella chart for deploying a KYPO CRP head services
type: application
version: 1.1.5
appVersion: "22.06"
dependencies:
  - name: kypo-git-internal
    version: 1.0.0
    repository: file://charts/kypo-git-internal
    condition: kypo-git-internal.enabled
  - name: kypo-oidc
    version: 1.0.0
    repository: file://charts/kypo-oidc
    condition: kypo-oidc.enabled
  - name: kypo-guacamole
    version: 1.0.0
    repository: file://charts/kypo-guacamole
    condition: kypo-guacamole.enabled
