apiVersion: v2
name: training-feedback
description: Training-feedback service Helm chart
type: application
version: 1.0.1
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
