{{- $ports := list (dict "port" .Values.global.services.answersStorage.port "protocol" "TCP" "probe" true) -}}
{{- include "common.deployment.header" (dict "name" .Values.global.services.answersStorage.name "replicasCount" .Values.replicasCount "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.services.answersStorage.name "ports" $ports "Values" .Values) }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - "/opt/java/openjdk/bin/keytool -importcert -alias kypo -file /srv/tls.crt -cacerts -storepass changeit -noprompt"
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
