{{- define "common.labels" -}}
app.kubernetes.io/name: {{ .chart.Name }}
helm.sh/chart: {{ .chart.Name }}-{{ .chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .release.Service }}
app.kubernetes.io/instance: {{ .release.Name }}
app.kubernetes.io/part-of: KYPO-CRP
{{- range $key, $val := .extraLabels }}
{{ $key }}: {{ $val }}
{{- end}}
{{- end -}}
